### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by DalioKim** [ReleaseAppUntilDie/GatheRunner#47]
- [x] 1. 리터럴 변수 선언
- [x] 2. LocationManger 뷰모델로 변경
- [ ] 3. Formating, Lint 커스텀 (2차)
- [ ] 4. SwiftGen 적용 (2차)
- [x] 5. GoggleInfoPlist 파일
- [ ] 6. Localizable (2차)
- [x] 7. FieldStyle 오탈자 수정 
- [x]  8. 머지실수로 인한 AuthView 복구
- [ ]  9. Network Error 정의 및 재시도 (2차)
- [x]  10. SelectedTab 환경변수 잘못된 사용 수정(변경이 없으니 싱글턴으로 사용)
- [x]  11. 중복회원 알림, 로딩바등 UI/UX 처리
