### ISSUE TITLE
Todo: wh5929

### ISSUE THREAD

**Issue by wh5929** [ReleaseAppUntilDie/GatheRunner#64]
아래의 PR에서 나온 Review 일부 반영
https://github.com/ReleaseAppUntilDie/GatheRunner/pull/58#top

## Bug Fix
- [x] MapView 코드를 분리한 후 hidden() / isEmpty() 사용시 적용 되지 않는 문제
- [x] fullScreenCover dismiss 될때 애니메이션이 매끄럽지 않게 표시되는 문제
- [x] #66
- [x] RunGuideTabView 객체 범위(터치 범위)가 객체 크기를 벗어나는 문제

## Refactor
- [x] RunGuideTabView - UI와 로직 분리 작업
- [x] FullScreenCoverView onChanged, onEnded 이벤트 분리

## UI 변경
- [x] #75
- [x] RunningGuideView.swift 에서 카드 모양의 뷰를 담은 컨테이너 뷰가 화면 하단의 MainTabBar 와 겹쳐 보이는 문제 해결하기
- [x] 러닝 가이드 카드뷰 텍스트(흰색)와 배경색과 유사한경우 글자가 잘 보이지 않는 증상 수정하기
- [x] fullScreenCover 창에서 일부분(텍스트) 미려한 UI 로 구성
- [x] Light Mode Only 설정

## Research
- [ ] 바로 시작 <-> 러닝 가이드 뷰 전환시 버벅이지 않도록 인스턴스를 미리 생성해두거나, 인스턴스를 해제시키지 않도록 구현해보기
- [ ] 총 이동 경로 / 정해진 기간 또는 / 주로 활동한 장소를 기반으로 히트맵 만들어보기(Jason에게 이동경로 데이터 저장해줄것을 요청해야 함) -> 히트맵을 aod나 영상으로 전환시켜보기
- [ ] RunGuideDetailDescriptionView에서 드래그 가속도 반영 및 반응 속도 빨라질 수 있도록 수정
- [ ] Dynamic Island 사용해보기 -> 현재 심박수나(심박수 반영은 안하지만...) 페이스 등을 시각화 하여 표시하면 좋을듯
