### ISSUE TITLE
Todo: wh5929 / Until - 1차 프로젝트 마감(11/18)

### ISSUE THREAD

**Issue by wh5929** [ReleaseAppUntilDie/GatheRunner#70]
## 기능 추가
- [ ] openAPI 또는 Apple WeatherKit(ios16 부터 지원) 이용하여 날씨 정보 받아와서 러닝하기 적합한 날씨 여부 확인 및 추천해주기 -> 한달안에 구현 가능하다면 푸시알림으로 / 그렇지 않다면 러닝뷰에서 사용자가 확인할 수 있도록 구현하기
- [x] Firebase 를 통해 가져온 정보를 이용해 ViewModel 구성하기
- [x] (환경)설정 View 에서 사용자 위치 정보 수집(위치 서비스)을 on/off 할 수 있는 토글을 만들고, 앱이 실행되었을때 현재 위치(시군구 정보만 추출) 확인 후 runningGuideTabView 의 맨 앞페이지에 운동지수 정보를 표시하기
- [ ] GPS 정보를 수신해 현재 러닝 상태를 나타내는 기능 구현

## UI 변경
- [x] BottomButtonsView 의 설정, 음악 버튼 제거(음악 재생 기능 구현 안할 예정)
- [ ] 날씨 정보 확인할 수 있도록 UI 변경 및 구성
- [ ] RunGuideDetailDescriptionView 의 BottomView 에 적절한 컨텐츠 채우기

## 앱 등록 관련
- [ ] 제품 페이지 미리 보기
- [ ] 지원 URL, 마케팅 URL 내용 확인해보기
