### ISSUE TITLE
Todo: All

### ISSUE THREAD

**Issue by wh5929** [ReleaseAppUntilDie/GatheRunner#80]
### 앱스토어 등록을 위한 작업
- [ ] (환경)설정 View 만들어서 firebase 사용자 계정 탈퇴할 수 있도록 처리 및 firebase 와 연동해서 gatherunner cloud firestore의 사용자 계정 삭제하도록 구성하기 -> 계정 삭제 버튼 시 Alert 창 띄우며 데이터가 모두 삭제됩니다. 정말 삭제하겠습니까? 와 같은 문구로 사용자에게 알려야 한다.
- [ ] (환경)설정 View 는 HeaderView 의 우측 + 버튼 자리에 대체 하는건 어떨까? 러닝뷰에서만 보이도록 해도 괜찮을듯하다.
- [x] 회원탈퇴 및 로그아웃 되었을때의 화면 구성에 대해 고려해보기 -> 예) 회원탈퇴가 완료되었다는 Alert 및 View 실행 후 러닝뷰로 전환
- [x] firebase 사용자 계정 로그인 UI 화면 구현하기(자체 제공 UI 사용 or 로그인 뷰를 따로 만듬)
- [ ] 개인정보 처리 방침 만들기 -> 사용자 계정을 어떻게 보관하고 있는지 개인정보 처리 방침을 담은 URL 링크 제공하기 ( [링크 참조](https://atelier-chez-moi.tistory.com/85) )
- [ ] 위치기반 서비스 이용약관 만들기
- [ ] 면책조항 필요하다면 이용 -> [링크](https://app.termsfeed.com/wizard/disclaimer#step-4)
- [ ] Apple mac silicon 지원 X 설정
- [ ] 앱 첫 실행시 런치스크린 -> 약관 동의 화면으로 넘어감 -> 아래 사진과 비슷하게 구현
- [ ] spm으로 전환

<img width="493" alt="image" src="https://user-images.githubusercontent.com/10336586/199205605-ee7469ab-c6cb-4e10-8e64-e0dabe02e4ac.png">
